
default: &default
  adapter: sqlite3
  encoding: unicode
  pool: 5
  username: admin
  password: password

development:
  <<: *default
  database: petrohub_db



test:
  <<: *default
  database: petrohub_test_db


production:
  <<: *default
  adapter: postgresql
  database: petrox_production
  username: petrox
  password: <%= ENV['PETROX_DATABASE_PASSWORD'] %>
